branches:
  except:
  - appveyor

language: cpp

addons:
  apt:
    packages:
    - libusb-1.0-0-dev
    - libftdi-dev

matrix:
  include:
    # macOS 10.14 and Xcode 11.2.1
    - os: osx
      osx_image: xcode11.2

    # macOS 10.15.5 and Xcode 12.0
    - os: osx
      osx_image: xcode12

    # Ubuntu LTS, gcc, x64
    - os: linux
      dist: bionic
      compiler: gcc

    # Ubuntu LTS, Clang, x64
    - os: linux
      dist: bionic
      compiler: clang

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew install libftdi;
    fi

before_script:
  - cmake --version

script:
  - mkdir build && cd build
  - cmake ..
  - make
