branches:
  except:
  - appveyor

language: cpp

env:
  - HOMEBREW_NO_AUTO_UPDATE=1

addons:
  apt:
    packages:
    - libusb-1.0-0-dev
    - libftdi-dev
  homebrew:
    packages:
    - libftdi

matrix:
  include:
    # macOS 10.15.7 and Xcode 12.2
    - os: osx
      osx_image: xcode12.2

    # macOS 12.4 and Xcode 13.4.1
    - os: osx
      osx_image: xcode13.4

    # Ubuntu LTS, gcc, x64
    - os: linux
      dist: bionic
      compiler: gcc

    # Ubuntu LTS, Clang, x64
    - os: linux
      dist: bionic
      compiler: clang

before_script:
  - cmake --version

script:
  - mkdir build && cd build
  - cmake ..
  - make
